backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # Ο φάκελος που θα αποθηκεύονται τα αρχεία σου
public_folder: "/uploads" # Ο φάκελος από όπου θα εμφανίζονται δημόσια τα αρχεία σου

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts" # Φάκελος όπου θα αποθηκεύονται τα άρθρα που γράφεις
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Περιγραφή", name: "description", widget: "text" }
      - { label: "Κείμενο", name: "body", widget: "markdown" }
