backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Περιγραφή", name: "description", widget: "text" }
      - { label: "Κείμενο", name: "body", widget: "markdown" }

local_backend: true

site_url: https://roadtrip-travel-gr.netlify.app
auth:
  identity_url: https://roadtrip-travel-gr.netlify.app/.netlify/identity
  gateway_url: https://roadtrip-travel-gr.netlify.app/.netlify/git
  backend_login_path: /admin/
  auth_type: implicit
  app_id: X36a5DLYqgbsw1NZ8j1vQUL1vxRoectA
  base_url: https://dev-uj4ar6kzrbxng5kt.us.auth0.com
  auth_endpoint: authorize
