backend:
  name: auth0
  domain: dev-uj4ar6kzrbxng5kt.us.auth0.com
  client_id: X36a5DLYqgbsw1NZ8j1vQUL1vxRoectA
  redirect_uri: https://roadtrip-travel-gr.netlify.app/admin/

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Περιγραφή", name: "description", widget: "text" }
      - { label: "Κείμενο", name: "body", widget: "markdown" }

