backend:
  name: github
  repo: palaki24/Roadtrip-Travel-GR
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Περιγραφή", name: "description", widget: "text" }
      - { label: "Κείμενο", name: "body", widget: "markdown" }
